language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t lucpas/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true lucpas/react-test npm test

after_success:
  # Build production images
  - docker build -t lucpas/fibo-client ./client
  - docker build -t lucpas/fibo-nginx ./nginx
  - docker build -t lucpas/fibo-server ./server
  - docker build -t lucpas/fibo-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take images and push them to docker hub
  - docker push lucpas/fibo-client
  - docker push lucpas/fibo-nginx
  - docker push lucpas/fibo-server
  - docker push lucpas/fibo-worker
  
#deploy:
#  provider: elasticbeanstalk
#  region: us-west-1
#  app: multi-docker
#  env: MultiDocker-env
#  bucket_name: elasticbeanstalk-us-west-1-306476627547
#  bucket_path: docker-multi
#  on:
#    branch: master
#  access_key_id: $AWS_ACCESS_KEY
#  secret_access_key:
#    secure: $AWS_SECRET_KEY
